### PR TITLE
Fix case sensitive nouns for k8s-1.11

### PR DESCRIPTION
**Pull request by Deepak-Routray**
Changed ConfigMap key to configMap in statefulset specs for Rundeck and Openam chart

### CODE REVIEW

**Review by rustycl0ck — APPROVED** [review]

**Comment by rustycl0ck** [comment]
Can we get 1 or 2 more approvals on this before merging? @darkyat @mpratsch

**Comment by dcwangmit01** [comment]
Why is the tar.gz for rundeck 0.1.0 regenerated?

**Comment by dcwangmit01** [comment]
MUST: Exclude rundeck-0.1.0.tgz from this PR.  Afterwards, mergeable.

**Comment by ghost** [comment]
Looks like you should re-run awake @Deepak-Routray and squash.

**Pull request merged**
