### PR TITLE
Update metrics-server charts

### PR DESCRIPTION
**Pull request by mpratsch**
I took the chart what is available in charts stable and tried to merge it with the current one.
Since we need to put an additional command (?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250&insecure=true")  to the image command line we need that.
Without the kubeletPort given it tries to connect to port 10255 (form. heapster) what is not available anymore. I think this is fixed in a higher k8s version.
We are running v1.9.5 on Platform 3.
Note: kubelet_authentication_token_webhook must be true but that is set as default in the kubespray commit c192a01b20608379510f030320ee4754eae444b7.

Features:
* This chart also supports RBAC
* Enables kubectl top
* Includes mem/cpu limits

PS: I'll try to fix that for the chart stable repo that we can get rid of that one.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Need link to upstream PR. Can't tell where the changes are without it.  Also, see the platform-deploy agreement file. Thanks!

**Comment by mpratsch** [comment]
@josdotso: Thanks, I hope I did that the right way now.
The upstream PR: https://github.com/helm/charts/pull/6795/commits
I only difference in this chart is the version number since we use version 0.1.0 already I had to increase it to 0.2.0 but the original upstream version would be 0.1.0 if my changes get merged.

**Comment by dcwangmit01** [comment]
There are some upstream comments that need to be taken care of.  After that, looks fine.

**Comment by mpratsch** [comment]
I'm going to close this PR.
The changes I needed are already merged in the stable repo since last Thursday.
See: https://github.com/helm/charts/commit/c488642dfeed2fc5abecfeb4a7c9634c3431ebbf

**Pull request closed without merging**
